const MESSAGES = [
  "🌍 Good morning, {name}! Where are you setting up camp today?",
  "📍 Hey {name}, quick one - office, home, or somewhere else today?",
  "👋 Morning, {name}! Drop your location so we know where to find you.",
  "🖥️ {name}, where's your desk today? Office, home, or wild card?",
  "🗺️ Location check, {name}! Where are you plugged in today?",
  "🌤️ Rise and shine, {name}! What's your base of operations today?",
  "🤝 Hey {name}, checking in - where are you working from today?",
  "🚀 {name}, mission briefing: what's your launch pad today?",
  "🏢 Office or remote today, {name}? Let us know!",
  "💻 {name}, where's your command center set up today?",
  "🌆 Top of the morning, {name}! Share your work spot for today.",
  "📅 {name}, office vibes or home vibes today? Drop your location!",
  "🤔 {name}, where are you being brilliant from today?",
  "🏠 Home, office, or surprise location, {name}? We're curious!",
  "🧭 {name}, what are today's coordinates? Let us know your location.",
  "🎪 Hey {name}! Main stage or backstage today? Share your location.",
  "⚡ Quick ping, {name} - where are you dialing in from today?",
  "🌅 New day, new location? {name}, let us know where you'll be!",
  "☕ Coffee's ready, {name}! Now tell us - where are you working today?",
  "🗓️ {name}, help us plan the day - what's your work location?",
  "📱 Buzz buzz, {name}! Where's your workspace today?",
  "🌐 {name}, what corner of the world are you working from today?",
  "🎯 {name}, where are you locking in and getting things done today?",
  "🛋️ Couch, desk, or co-working space, {name}? What's the vibe today?",
  "🔔 Ding! {name}, time to share your work location for the day.",
  "🎒 {name}, are you on-site or off-site today? Let us know!",
  "🧳 Packed for office or staying home, {name}? Drop your location.",
  "🌻 Good morning, {name}! Where's the productivity happening today?",
  "🗼 {name}, what's your HQ for the day? Share your spot!",
  "🎧 Headphones on, {name}? Tell us where you're zoning in from today.",
  "📌 Pin your location, {name}! Where are you working from today?",
  "🏖️ Desk, sofa, or beach? {name}, where are you logging in from today?",
  "🔑 {name}, unlock the day - tell us your work location!",
  "🌈 Happy morning, {name}! What's your work setup today?",
  "🧊 Cool check-in, {name}: where are you stationed today?",
];

// Fun facts refreshed July 2026: verified against NASA, UNESCO, Guinness, Nature,
// PLoS, Britannica, NIST, etc. Weighted toward India, Vietnam/Asia and universal
// science (US-only pop-culture and debunked "facts" removed). 172 entries.
// If you replace this list, reset the currentFact Script Property to 0.
const TRIVIA = [
  "Fish 'cough' to clear debris out of their gills. 🐟",
  "In 2023, India's Chandrayaan-3 became the first mission ever to land near the Moon's south pole - making India only the fourth country to reach the Moon's surface. 🌗",
  "Laughing is older than language - even tickled apes 'laugh.' 😂",
  "In Sweden, blood donors get a text when their blood is used to help someone. 🩸",
  "Earth has more trees - over 3 trillion of them - than there are stars in our Milky Way galaxy. 🌳",
  "The Moon drifts about 3.8 cm further away from Earth every year. 🌙",
  "Playing board games is linked to a lower risk of dementia. 🎲",
  "The tiny tardigrade, or 'water bear,' can survive the raw vacuum of space - some lasted 10 days in orbit, then came home and laid healthy eggs. 🐻",
  "Vietnam's Hang Son Doong is the world's largest cave - so vast it has its own jungle, river, and clouds inside. 🕳️",
  "The Eiffel Tower was originally meant to be taken down after 20 years. 🗼",
  "Swiss law effectively requires you to keep guinea pigs in pairs, because they get lonely. 🐹",
  "A single teaspoon of a neutron star would weigh billions of tonnes - its matter is packed as tightly as an atom's nucleus. ⭐",
  "Koala fingerprints are so human-like they can confuse a crime scene. 🐨",
  "Queen Elizabeth II trained as a mechanic and truck driver during World War II. 🔧",
  "Wood frogs freeze almost solid in winter and thaw back to life in spring. 🐸",
  "India reached Mars orbit on its very first attempt - and the Mangalyaan mission cost less to build than the Hollywood film 'Gravity.' 🚀",
  "Polar bears have black skin underneath their see-through, white-looking fur. 🐻‍❄️",
  "A day on Venus is longer than its year - it spins slower than it orbits the Sun. 🪐",
  "Chilled to about -271°C, helium becomes a 'superfluid' with zero friction - it can even creep up and over the walls of its container. 🧪",
  "Japanese macaques make snowballs and play with them for fun. ⛄",
  "Naked mole-rats can survive around 18 minutes with no oxygen. 🐁",
  "Scientists once levitated a live frog using powerful magnets. 🐸",
  "Vietnam is the world's second-largest coffee producer and its robusta powerhouse - the beans behind most of the world's instant coffee. ☕",
  "Beavers don't live in their dams - they build separate lodges behind them. 🦫",
  "Sharks are older than trees - they've been around for over 400 million years. 🦈",
  "Your phone's GPS stays accurate only because engineers correct its satellites for Einstein's relativity - time really does tick faster up in orbit. 🛰️",
  "Astronauts left a family photo on the Moon during Apollo 16. 🌑",
  "It rains methane on Titan, Saturn's largest moon. 🌧️",
  "Toy dog breeds like Chihuahuas have some of the largest brains relative to body size - though it doesn't make them the smartest. 🐕",
  "Around 300 years before Leibniz, the 14th-century Kerala mathematician Madhava worked out an infinite series to calculate pi. 📐",
  "The deep-sea glass sponge is among the longest-lived animals on Earth - one was estimated at about 11,000 years old. 🧽",
  "Identical twins do not have the same fingerprints. 👯",
  "A jellyfish called Turritopsis can revert from an adult back into its baby stage - which is why it's nicknamed 'the immortal jellyfish.' 🪼",
  "Emperor penguins can dive as deep as 550 metres. 🐧",
  "You can play with a yo-yo in space - an astronaut tried it on the Space Station. 🪀",
  "Every Holstein cow's black-and-white pattern is unique, like a fingerprint. 🐄",
  "Vietnamese water puppetry is about 1,000 years old - performed on water, with the puppeteers hidden waist-deep behind a screen. 🎭",
  "Axolotls can regrow lost limbs - and even parts of their brain. 🦎",
  "Earth's day is slowly getting longer - by roughly 1.8 seconds per century. 🌍",
  "Helium was discovered on the Sun before it was ever found on Earth - spotted in sunlight in 1868 and named after the Greek sun god. ☀️",
  "Greenland sharks can live for more than 400 years. 🦈",
  "The universe has an average colour, and scientists named it 'Cosmic Latte.' ☕",
  "Finland hosts a Mobile Phone Throwing World Championship. 📱",
  "Told that the number 1729 seemed 'dull,' India's Ramanujan instantly replied that it's the smallest number that is a sum of two cubes in two different ways. 🚕",
  "The oldest dog on record, an Australian cattle dog named Bluey, lived 29 years and 5 months. 🐶",
  "Most orange cats are male, by about three to one - and in 2025 scientists finally pinned down the gene behind their colour. 🐈",
  "The metal gallium melts in the warmth of your hand - it turns to liquid at just below body temperature. 🌡️",
  "Honeypot ants store food by swelling their own bodies into living pantries. 🐜",
  "Cows have best friends and get stressed when they're separated. 🐄",
  "Astronauts say space smells like seared steak, hot metal, and gunpowder. 🚀",
  "Vietnamese has six tones, so a single syllable said six different ways can mean six completely different things. 🎵",
  "Sheep can recognise and remember human faces. 🐑",
  "Salvador Dali paid restaurant bills by drawing on the cheques, knowing no one would cash them. 🎨",
  "Millions of tonnes of dust blow off the Sahara and across the Atlantic each year, fertilising the Amazon rainforest. 🏜️",
  "Your nose can tell apart about a trillion different smells. 👃",
  "Abraham Lincoln is the only U.S. president who ever held a patent. 💡",
  "Simon Bolivar helped liberate five South American countries. 🌎",
  "In 1980, Bengaluru-born Shakuntala Devi multiplied two random 13-digit numbers in her head in 28 seconds - a Guinness record. 🧮",
  "Antarctica is the largest desert on Earth. 🏜️",
  "Elephants comfort each other by gently stroking with their trunks. 🐘",
  "The centre of the Earth is roughly as hot as the surface of the Sun - both around 5,500°C. 🌋",
  "Sea otters hold hands while they sleep so they don't drift apart. 🦦",
  "The ruins of Pompeii include ancient take-out food counters. 🍲",
  "Giraffes hum to each other during the night. 🦒",
  "Near Da Nang, Vietnam's Golden Bridge looks like it's held up by two giant hands, sculpted to resemble weathered ancient stone. 🌉",
  "Vietnam grows roughly 35-40% of the world's black pepper - and handles over half of the world's pepper exports. 🌶️",
  "Google's founders once tried to sell the whole company for under $1 million. 💻",
  "Your brain is only about 2% of your body weight but burns roughly 20% of your energy, even at rest. 🧠",
  "Bats aren't blind - they see well and use echolocation too. 🦇",
  "Sleep 'power-washes' your brain, flushing out waste through fluid. 🧠",
  "A penguin at Edinburgh Zoo has been knighted and promoted to brigadier. 🐧",
  "The 'father of fibre optics' - the technology behind today's internet - was Punjab-born physicist Narinder Singh Kapany. 🔬",
  "After breathing pure oxygen first, a Croatian freediver held his breath underwater for a record 29 minutes in 2025. 🫁",
  "A shrimp's heart is located in its head. 🦐",
  "The first computer 'bug' was a real one - a moth found inside a Harvard computer in 1947 and taped into the logbook. 🐛",
  "There are stone circles even older than Stonehenge. 🪨",
  "Cuckoos lay their eggs in other birds' nests and let them do the parenting. 🐦",
  "Dogs tilt their heads to better pick out familiar words. 🐶",
  "Ha Long Bay means 'descending dragon' - legend says a dragon scattered the emerald bay's 1,000-plus limestone islands. 🐉",
  "The only known T. rex skin impressions show scales - so the giant adult probably wasn't feathered, even if some smaller cousins were. 🦖",
  "A single horse can produce far more than one horsepower - up to about 15. 🐎",
  "About 99% of the world's international internet traffic travels through fibre-optic cables lying on the ocean floor. 🌐",
  "'Tsundoku' is the Japanese word for buying books and never reading them. 📚",
  "'Petrichor' is the name for the earthy smell of rain. 🌧️",
  "A snail's tongue can carry thousands of microscopic teeth. 🐌",
  "India's UPI system now handles close to half of all real-time digital payments made anywhere in the world. 📱",
  "Cats were first domesticated around 9,500 years ago. 🐱",
  "Genghis Khan granted religious freedom across his empire. 🏹",
  "Shuffle a deck of cards well and you've almost certainly made an order that has never existed before - there are more ways to arrange 52 cards than there are atoms in the Earth. 🃏",
  "In 1930 the BBC announced 'there is no news' and played piano music instead. 📻",
  "A reindeer's eyes change from gold in summer to blue in winter. 🦌",
  "Melbourne gave its trees email addresses - and people started writing them love letters. 🌳",
  "Bhutan is the world's only carbon-negative country - its forests soak up far more CO2 than the whole nation emits. 🌲",
  "Apollo 17 astronaut Harrison Schmitt found out he was allergic to Moon dust. 🌕",
  "NASA's X-43 is the fastest jet ever built - it reached about 11,854 km/h. 🚀",
  "In any random group of just 23 people, it's more likely than not that two of them share the same birthday. 🎂",
  "Comets can smell like rotten eggs, ammonia, and almonds. ☄️",
  "From 1959 until satellite channels arrived in the early 1990s, Indian TV meant a single state broadcaster: Doordarshan. 📺",
  "Wearing a tight tie can reduce blood flow to your brain by about 7.5%. 👔",
  "Delhi's 1,600-year-old Iron Pillar has barely rusted - its unusual iron quietly grows its own protective coating. 🏛️",
  "Horseshoe crabs have blue blood that has helped save human lives. 🦀",
  "Flowers only appeared on Earth around 130 million years ago. 🌸",
  "Woolly mammoths were still alive when the ancient Egyptians were building the pyramids. 🦣",
  "Scotland's official national animal is the unicorn. 🦄",
  "A double rainbow's second arc has its colours in reverse order. 🌈",
  "Martin Luther King Jr. once got a C in a public speaking class. 🎤",
  "Japan's bullet train got its long nose from a bird - engineers copied a kingfisher's beak to make it quieter and faster. 🐦",
  "Newborn babies have about 100 more bones than adults do. 🦴",
  "A pistol shrimp snaps its claw so fast it creates a bubble hotter than lava. 🦐",
  "At least half of the oxygen you breathe is made by microscopic plankton in the ocean - not by forests. 🌊",
  "Goats have rectangular pupils, giving them a very wide field of view. 🐐",
  "Africa is the only continent that sits in all four hemispheres. 🌍",
  "Taipei's garbage trucks play Beethoven's 'Fur Elise' so people know to bring out the trash. 🎶",
  "Jaipur's 18th-century Jantar Mantar has a 27-metre stone sundial that still tells the time to within about two seconds. 🕰️",
  "The belief that paper can't be folded in half more than 8 times is a myth - a student folded a single sheet 12 times in 2002. 📄",
  "Marie Curie is the only person to win Nobel Prizes in two different sciences. 🥼",
  "The word 'robot' is only about a century old - it comes from a Czech word for forced labour and first appeared in a 1920 play. 🤖",
  "The woman who founded Mother's Day later campaigned to abolish it. 🌸",
  "The 'new car smell' is actually a mix of more than 200 different chemicals. 🚗",
  "Avocados only ripen after they're picked, never on the tree. 🥑",
  "Singapore purifies used water into ultra-clean 'NEWater' - clean enough to supply up to 40% of the country's water needs. 💧",
  "Flamingos are born grey and turn pink from the food they eat. 🦩",
  "Continental plates drift about as fast as your fingernails grow. 🌍",
  "Sound travels about four times faster through water than through air. 🔊",
  "Ganymede, one of Jupiter's moons, is larger than the planet Mercury. 🌕",
  "A starfish is basically all head - it has no body. ⭐",
  "The Statue of Liberty was a shiny copper-brown before it slowly turned green. 🗽",
  "Mawsynram, a village in Meghalaya, records the highest average annual rainfall on Earth - close to 12 metres a year. 🌧️",
  "The medical name for brain freeze is 'sphenopalatine ganglioneuralgia.' 🍦",
  "Kea parrots have an 'infectious laugh' - a happy call that spreads through the flock. 🦜",
  "The Sun holds about 99.8% of all the mass in our entire solar system. 🌞",
  "France requires large supermarkets to donate or compost unsold food. 🥖",
  "A U.S. Navy base is partly guarded by trained bottlenose dolphins. 🐬",
  "The ampersand (&) comes from the Latin word 'et,' meaning 'and.' 🔣",
  "In the Philippines, the Puerto Princesa river runs 8 km through a mountain cave before flowing into the sea - and its lower reaches rise and fall with the tides. 🚣",
  "Dogs can learn around 250 words - roughly like a 2-year-old child. 🐕",
  "A lightning bolt is about five times hotter than the surface of the Sun. ⚡",
  "Mercury and bromine are the only two elements that are liquid at ordinary room temperature. ⚗️",
  "The largest butterfly, the Queen Alexandra's Birdwing, has a wingspan of about 31 cm. 🦋",
  "Mauna Kea is taller than Mount Everest when measured from its base on the seafloor. 🌋",
  "A badminton shuttlecock's feathers all come from the same wing of a goose, so they all spin the same way. 🏸",
  "In rain-soaked Meghalaya, Khasi villagers don't build their bridges - they grow them from living tree roots over decades. 🌱",
  "The quietest place on Earth is a Microsoft lab measured at -20.6 decibels. 🔇",
  "LEGO keeps a secret vault holding every set the company has ever made. 🧱",
  "You're about a centimetre taller in the morning than at night - your spinal discs slowly compress as the day goes on. 📏",
  "Sperm whales can dive nearly 3 km down to hunt giant squid. 🐋",
  "A rodent's front teeth never stop growing. 🐀",
  "Ethiopia's calendar has 13 months. 📅",
  "Korea's Hangul is one of the only alphabets in history with a known inventor and launch date - King Sejong unveiled it in 1446. ✍️",
  "Jupiter has the shortest day of any planet - it spins once in about 10 hours. 🪐",
  "The peregrine falcon is the fastest animal, diving at around 240 mph. 🦅",
  "Oxford University was already teaching students before the Aztec capital of Tenochtitlan was even founded. 📚",
  "'Deja reve' is the eerie feeling that you've dreamed something before. 💭",
  "Neil Armstrong's astronaut application arrived late - a friend slipped it into the pile. 🚀",
  "Bumblebees have been found flying more than 3 km above sea level. 🐝",
  "Every winter, over 100,000 flamingos turn the mudflats of Mumbai's Thane Creek pink. 🦩",
  "Albatrosses can stay airborne for months at a time and circle the globe. 🕊️",
  "You carry roughly as many bacterial cells as your own cells - about 1.3 to 1, not the '10 to 1' often repeated. 🦠",
  "Silbo Gomero is a real whistled language, used to 'talk' across the deep valleys of one of the Canary Islands. 🏝️",
  "Crows understand simple physics about as well as a 6-month-old baby. 🐦‍⬛",
  "On average, Mercury is the closest planet to Earth. 🪐",
  "'Four' is the only number in English spelled with as many letters as its value. 4️⃣",
  "The Komodo dragon - the world's largest lizard, up to 3 metres long - lives wild nowhere on Earth except Indonesia. 🦎",
  "Peru is the only country whose English name can be typed on a single keyboard row. ⌨️",
  "In colonial America, lobster was so common it was fed to prisoners. 🦞",
  "Pune's Serum Institute is the world's largest vaccine maker - by its own estimate, most of the world's children get at least one vaccine made there. 💉",
  "Hippos can't actually swim - they push off the riverbed and 'gallop' underwater. 🦛",
  "Barcelona has playgrounds designed specifically for senior citizens. 🛝",
  "The little dot above a lowercase 'i' or 'j' is called a 'tittle.' 🔤",
  "The word 'shampoo' comes from the Hindi 'champo,' meaning to press or massage, and entered English back in the 1760s. 🧴",
  "Cashews grow attached to a fruit called the cashew apple. 🥜",
  "Volvo gave away its three-point seatbelt patent so other carmakers could save lives. 🚗",
];

function doPost(e) {
  try {
    if (!e.postData || !e.postData.contents) {
      throw new Error("No postData or contents in the request");
    }

    const data = JSON.parse(e.postData.contents);
    const email = (data.email || "").toString().trim();
    const date = (data.date || "").toString().trim();
    const status = (data.status || "").toString().trim();
    logToDumpSheet(`Sheet write request: email=${email}, date=${date}, status=${status}`);

    if (!email || !date || !status) {
      return jsonOutput_({ success: false, message: "Missing email, date, or status" });
    }

    const result = updateLocationByEmailID(email, status, date);
    logToDumpSheet(`Sheet write result for ${email}: ${JSON.stringify(result)}`);
    return jsonOutput_(result);
  } catch (error) {
    logToDumpSheet('Error in doPost: ' + error.toString());
    return jsonOutput_({ success: false, error: error.toString() });
  }
}

function jsonOutput_(obj) {
  return ContentService.createTextOutput(JSON.stringify(obj))
    .setMimeType(ContentService.MimeType.JSON);
}

// Logs a message to the "DUMP" sheet of the active spreadsheet for debugging or data tracking purposes.
function logToDumpSheet(message) {
  try {
    const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('DUMP');
    const timestamp = new Date();
    sheet.appendRow([timestamp, message]);
  } catch (error) {
    Logger.log('Error logging to DUMP sheet: ' + error.toString());
  }
}
